config/routes.rb
Rails.application.routes.draw do

  resources :admin, only: [:edit, :update]
  get '/signup', to: 'users#new'
  get "sessions/two_factor"
  post "sessions/authy_verify"
  post "sessions/authy_send_token"

  namespace :twilio do
    post 'messages', to: 'messages#create'
  end

  resources :sessions, only: [:new, :create]
  delete "sessions/destroy"
  root 'static_pages#home'
  
  resources :users, only: [:new, :create, :edit, :destroy]
  resources :users, only: [:index, :update, :show,] do
    member do
      get 'change_role_to_admin'
      get 'change_role_to_worker'
      get 'delete_an_worker'
	  end
  end
  namespace :twilio do
    post 'messages', to: 'messages#create'
  end
  resources :users do
    member do
      get :following, :followers
    end
  end
  
  resources :relationships, only:[:create, :destroy] do
      member do
        post 'follow'
        delete 'unfollow'
      end
  end
  
  resources :account_activations, only: [:edit]
  #resources :whatsapp_messages, only: [:create, :show]  
  resources :microposts, only: [:index, :create, :destroy, :show] do
    member do
      post 'collect_ids'
      
      get 'collect_ids'
    end
  end

resource :microposts do
  collection do
    post 'create'
  end
end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :microposts, dependent: :destroy
  attr_accessor :activation_token
  attr_accessor :current_password

	has_many :events, through: :microposts
  has_many :active_relationships, class_name:  "Relationship",
                                  foreign_key: "follower_id",
                                  dependent:   :destroy
  has_many :passive_relationships, class_name:  "Relationship",
                                   foreign_key: "followed_id",
                                   dependent:   :destroy
  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower

  #VALID_phone_REGEX = /\A(?:\+?(\d{1,2}))?(\d{1,10})\z/
  #before_save { self.email = email.downcase }
  
  before_create :create_activation_digest
  
  validates :name,  presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 50 }, format: { with: VALID_EMAIL_REGEX }, uniqueness: true
  VALID_phone_REGEX = /\A(\d{1,10})\z/
  validates :phone_number, presence: true, length: { maximum: 10 }, uniqueness: true, format: { with: VALID_phone_REGEX }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }
  validates :country_code, presence: true

  def follow(other_user)
    following << other_user
  end

  # Unfollows a user.
  def unfollow(other_user)
    following.delete(other_user)
  end

  # Returns true if the current user is following the other user.
  def following?(other_user)
    following.include?(other_user)
  end

   def self.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  # Returns a random token.
  def self.new_token
    SecureRandom.urlsafe_base64
  end
  
  def authenticated?(attribute, token)
    digest = send("#{attribute}_digest")
    return false if digest.nil?
    BCrypt::Password.new(digest).is_password?(token)
  end


private
def downcase_email
      self.email = email.downcase
    end

  def create_activation_digest
      self.activation_token  = User.new_token
      self.activation_digest = User.digest(activation_token)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
before_action :authenticate! ,  only: :show
before_action :logged_in_user , only: [:index, :edit, :update, :destroy, :change_role_to_admin, :change_role_to_worker, :delete_an_worker, :show]
before_action :correct_user,   only: [:edit, :update]
before_action :admin_user,     only: [:destroy, :index, :change_role_to_admin, :change_role_to_worker, :delete_an_worker]
before_action :send_otp, only: :edit
require 'will_paginate/array'
  # shows all users 
  def index
    @users = User.all.order(admin: :DESC)
    @users = @users.paginate(:page => params[:page], :per_page => 8)
  end
  
  # shows user profile
  def show
      @user = User.find(params[:id])
      @microposts = @user.microposts.paginate(:page => params[:page], :per_page => 5)
  end

  # create new user
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      UserMailer.account_activation(@user).deliver_now
      authy = Authy::API.register_user(
      email: @user.email,
      cellphone: @user.phone_number,
      country_code: @user.country_code )
      @user.update(authy_id: authy.id)
      flash[:info] = "Please check your email to activate your account."
      redirect_to root_url
    else
      render 'new'
    end
  end
  
  # update password
  def edit
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
    token = Authy::API.verify(id: @user.authy_id, token: params[:token])
    if token.ok?
    if @user.authenticate(params[:user][:current_password]) && @user.update_attributes(user_params)
      flash[:success] = "Password updated"
      redirect_to @user
      else
      flash.now[:danger] = "Invalid current password"
      render 'edit'
    end
  else
    flash.now[:danger] = "Invalid token"
      render 'edit'   
  end
end

  # delete user
  def destroy
   User.find(params[:id]).destroy
   flash[:success] = "Profile deleted"
   redirect_to users_path
  end

def send_otp
    if @user.id == session[:user_id]  
    Authy::API.request_sms(id: @user.authy_id)
    flash.now[:info] = "OTP has been sent to your phone. It is not set to default"
end
end

  def change_role_to_admin
    user = User.find(params['id'])
    user.total_votes = 0
    user.update_attribute(:admin, true)
    flash[:success] = "Promoted as admin"
    redirect_back(fallback_location: users_path)
  end
  
  def delete_an_worker
    user = User.find(params['id'])
    user.destroy
    flash[:success] = "Profile deleted"
    redirect_to users_path
  end
  
  def change_role_to_worker
    user = User.find(params['id'])
    if current_user.following?(user)
    flash[:info] = "Your Vote is deleted"
    current_user.unfollow(user)
    user.update_attribute(:total_votes, user.followers.count)
    else
    flash[:info] = "Your Vote is registered to remove admin "
    current_user.follow(user)
    user.update_attribute(:total_votes, user.followers.count)
    end
    if user.total_votes >= (0.75 * (User.where(admin: true).count))
      flash[:success] = "Removed admin"
      user.total_votes = 0
      user.update_attribute(:admin, false)
      redirect_to delete_an_worker_user_path
    else
      redirect_back(fallback_location: users_path)
    end
  end
  
  
  
 private
 def user_params
    params.require(:user).permit(:id, :name, :email, :current_password, :password, 
                                   :password_confirmation, :phone_number, :country_code, :admin)
  end
  
  def logged_in_user
    unless signed_in?
    flash[:danger] = "Please log in."
    redirect_to new_session_path
    end
  end
  
  def correct_user
    @user = User.find(params[:id])
    redirect_to(root_path) unless current_user?(@user)
  end
  
  def admin_user
      redirect_to(root_path) unless current_user.admin?
  end

end

app/helpers/users_helper.rb
module UsersHelper

  # Returns the Gravatar for the given user.
  #def gravatar_for(user)
    #gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
   # gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
  #  image_tag(gravatar_url, alt: user.name, class: "gravatar")
 # end
#end
#module UsersHelper

  # Returns the Gravatar for the given user.
  def gravatar_for(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/users/_follow.html.erb
<%= form_for(current_user.active_relationships.build, remote: true) do |f| %>
  <div><%= hidden_field_tag :followed_id, @user.id %></div>
  <%= f.submit "Follow", class: "btn btn-primary" %>
<% end %>

app/views/users/_follow_form.html.erb
  <div id="follow_form">
  <% if current_user.following?(@user) %>
    <%= render 'unfollow' %>
  <% else %>
    <%= render 'follow' %>
  <% end %>
  </div>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.active_relationships.find_by(followed_id: @user.id),
             html: { method: :delete }, remote: true) do |f| %>
  <%= f.submit "Unfollow", class: "btn" %>
<% end %>

app/views/users/_user.html.erb
<li>
      <%= gravatar_for user, size: 50 %>
      <%= link_to user.name, user %>
      <% if current_user.admin? && !current_user?(user) %>
      <% if user.admin? %>
      | Admin
      | Vote to delete
      <% else %>
      | <%= link_to "User", edit_admin_path(user),
      data: { confirm: "Promote as Admin"}%>
      | <%= link_to "delete", user, method: :delete, 
                                  data: { confirm: "You sure?" } %>
  <% end %>
  <% end %>
</li>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<h1>Update your profile</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control', :readonly => true %>
      
      <%= f.label :current_password, "Old password" %>
      <%= f.password_field :current_password, class: 'form-control' %>
      
      <%= f.label :password, "New password" %>
      <%= f.password_field :password, class: 'form-control' %>
      
      <%= f.label :password_confirmation, "Re-enter password" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>
      
      <%= label_tag :code, "Enter OTP sent to your registered Mobile number:" %>
      <%= text_field_tag :token, '', class: "form-control" %>

      <%= f.submit "Save changes", class: "btn btn-primary" %>
    <% end %>

    <div class="gravatar_edit">
      <%= gravatar_for @user %>
      <a href="http://gravatar.com/emails" target="_blank">change</a>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div><b class="logs">USERS:</b> <br>
<br></div>
<div class="table-responsive">
  <% if current_user.admin? %>
  <table class="table table-sm table-striped table-bordered table-hover">
    <thead bgcolor="#777", class="thead-dark">
      <tr>
        <th scope="col">Name</th>
        <th scope="col">Email</th>
        <th scope="col">Phone Number</th>
        <th scope="col">Role</th>
        <th scope="col">Action</th>
      </tr>
    </thead>
    <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= link_to user.name, user_path(user) %></td>
        <td><%= user.email %></td>
        <td><%= user.phone_number %></td>
        <% if user.admin? %>
        <td> <b class="btn btn-success btn-sm btnsm"><%= "Admin" %></b></td>
        <td>  <% if current_user.admin? && current_user != user%>
        <% if current_user.following?(user) %>
          <%= link_to 'Unvote-Remove Admin ', change_role_to_worker_user_path(user), :class => "btn btn-info btn-sm"%>
        <% else %>
          <%= link_to 'Vote-Remove Admin ', change_role_to_worker_user_path(user), :class => "btn btn-info btn-sm"%>
        <% end %>
        <b class="btn btn-warning btn-sm btnsm"><%= user.followers.count %> Voted </b>
        <% end %></td>
            <% else %>
              <td><b class="btn btn-success btn-sm btnsm"><%= "User " %></b></td>
              <td><% if current_user.admin? %>
                <%= link_to ' Promote as Admin', change_role_to_admin_user_path(user), :class => "btn btn-info btn-sm" %>
                <%= link_to ' Delete User', delete_an_worker_user_path(user), :class => "btn btn-danger btnsm" %>
              <% end %></td>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <% end %>
</div>
<%= will_paginate(@users) %>
<br><br><br>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign Up</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control'%>
      <h2>Enter a valid email address</h2>
      
      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.label :country_code %>
      <%= f.text_field :country_code, class: "form-control", value: "+91", :readonly => true %>
      
      <%= f.label :phone_number %>
      <%= f.text_field :phone_number, class: 'form-control', id: "authy-cellphone"%>
      <h2>Enter 10 digit Mobile number</h2>
      
      <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% if signed_in? %>
  <div class="row">
    <aside class="col-md-4">
      <section class="user_info">
        <%= render 'shared/user_info' %>
      </section>
      <% if session[:user_id] == @user.id %>
      <section class="micropost_form">
        <%= render 'shared/micropost_form' %>
      </section>
      <% end %>
    </aside>
    <div class="col-md-8">
      <div id="micropost_count">
      <% if @microposts.any? %>
      <h3>Microposts (<%= @microposts.count %>)</h3></div>
      <div id="micropost_refresh">
      <ol class="microposts">
      <% @microposts.each do |micropost| %>
      <li>   <%= render 'microposts/micropost', micropost: micropost %></li><% end %>
      </ol></div><% end %>
      <%= will_paginate(@microposts) %>
    </div>
</div>
<% else %>
<div class="center jumbotron">
    <h1>Welcome to Healthify App</h1>
    <p>

    </p>
    <%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary" %>
    <p><small>Please <%= link_to "Login", new_session_path %> if you have an account</small></p>
</div>

<%#= link_to image_tag("rails.png", alt: "Rails logo"),
            'http://rubyonrails.org/' %>
<% end %>