config/routes.rb
Rails.application.routes.draw do

  resources :admin, only: [:edit, :update]
  get '/signup', to: 'users#new'
  get "sessions/two_factor"
  post "sessions/authy_verify"
  post "sessions/authy_send_token"

  namespace :twilio do
    post 'messages', to: 'messages#create'
  end

  resources :sessions, only: [:new, :create]
  delete "sessions/destroy"
  root 'static_pages#home'
  
  resources :users, only: [:new, :create, :edit, :destroy]
  resources :users, only: [:index, :update, :show,] do
    member do
      get 'change_role_to_admin'
      get 'change_role_to_worker'
      get 'delete_an_worker'
	  end
  end
  namespace :twilio do
    post 'messages', to: 'messages#create'
  end
  resources :users do
    member do
      get :following, :followers
    end
  end
  
  resources :relationships, only:[:create, :destroy] do
      member do
        post 'follow'
        delete 'unfollow'
      end
  end
  
  resources :account_activations, only: [:edit]
  #resources :whatsapp_messages, only: [:create, :show]  
  resources :microposts, only: [:index, :create, :destroy, :show] do
    member do
      post 'collect_ids'
      
      get 'collect_ids'
    end
  end

resource :microposts do
  collection do
    post 'create'
  end
end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <nav>
    <small>
    <h2>Healthify 2019</h2>
  </small>
  <%= javascript_include_tag '//maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js', 'data-turbolinks-track' => true %>
  <%= yield :javascript %>

  </nav>
</footer>

app/views/layouts/_header.html.erb
<link rel="stylesheet" href="custom.scss">
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "HEALTHIFY", '#', id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <% if !signed_in? %>
          <li><%= link_to "Home",   root_path %></li>
          <li><%= link_to "Login",   new_session_path %></li>
        <% else %>
          <li><%= link_to "My Profile",   user_path(current_user) %></li>
          <li><%= link_to "Summary", micropost_path(current_user)  %></li>
          <li><%= link_to "Logs", microposts_path%></li>
          <% if current_user.admin? %>
            <li><%= link_to "Users", users_path %></li>
          <% end %>
          <li><%= link_to "Account", edit_user_path(current_user) %></li>
          <li><%= link_to "Log out", sessions_destroy_path, method: :delete %></li>
        <% end %>   
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
    <![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HEALTHIFY</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag    '//cdnjs.cloudflare.com/ajax/libs/authy-forms.css/2.2/form.authy.min.css', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
<%= javascript_include_tag '//cdnjs.cloudflare.com/ajax/libs/authy-forms.js/2.2/form.authy.min.js', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  
  <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
        <% end %>
    <%= yield %>
  <%= javascript_include_tag '//maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js', 'data-turbolinks-track' => true %>
  <%= yield :javascript %>
  <%#= debug(params) if Rails.env.development? %>
    <%= render 'layouts/footer' %>
  </div>
  </body>
</html>